//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZeissControllerX.rc
//
#define IDR_ZEISSCONTROLLER_MENU        6
#define IDD_ZEISSCONTROLLER_X_MAINDIALOG 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DATA_COLLECTION             131
#define BTN_INIT                        1001
#define BTN_GET                         1002
#define BTN_ABOUT_BOX                   1003
#define BTN_CREATE                      1004
#define BTN_CLOSE_CONTROL               1005
#define BTN_SET                         1006
#define BTN_EXEC                        1008
#define IDC_STATIC_MSG                  1009
#define IDC_SET_VALUE                   1010
#define IDC_EDIT_CMD_INS                1011
#define IDC_STATIC_CMD                  1012
#define IDC_EDIT_CMD_INS_TYPE           1013
#define IDC_STATIC_TYPE                 1014
#define BTN_CAPTURE                     1016
#define IDC_MoveStageMouse              1017
#define IDC_MOVESTAGE_X                 1018
#define IDC_MOVESTAGE_Y                 1019
#define IDC_OPN_DATA_COLLECTION         1021
#define ID_DC_BTN_CLOSE                 1022
#define ID_BTN_CLOSE                    1023
#define IDC_ANG_FROM                    1026
#define IDC_ANG_TO                      1027
#define IDC_DC_RECORD                   1028
#define IDC_DC_TRACK                    1029
#define IDC_DC_TIMERBASED               1030
#define IDC_DC_DELTA_Z                  1030
#define IDC_DC_ANGLEBASED               1031
#define IDC_DC_DELTA_T                  1031
#define IDC_DC_STATUS                   1032
#define IDC_DC_GAIN                     1032
#define IDC_DC_Imaging                  1033
#define IDC_DC_LIVESTREAMING            1033
#define IDC_DC_REVIEW_BTN               1034
#define IDC_DC_CONTINUOUS_RECRD_RDBTN   1035
#define IDC_DC_IMGBASED_RECRD_RDBTN     1036
#define IDC_DC_TIMER_BASED_TRCK_RDBTN   1037
#define IDC_DC_ANGLE_BASED_TRCK_RDBTN   1038
#define IDC_DC_IMG_BASED_TRCK_RDBTN     1039
#define IDC_DC_IMGBASED_RDBTN3          1040
#define IDC_DC_LINEAR_MOV_CHECKBTN      1040
#define IDC_DC_IMGBASED_ANGLEBASED_CHCKBTN 1041
#define IDC_DC_MOVEMOUSE_CHCKBTN        1042
#define IDC_DC_FIND_Z_HEIGHT_BTN        1043
#define IDC_DC_WAIT_CHCKBTN             1044
#define IDC_DC_SINGLERUN_CHCKBTN        1045
#define IDC_DC_READJUST_Z_CHCKBTN       1046
#define IDC_DC_QC_ALPHA                 1047
#define IDC_DC_QC_CAMLEN                1048
#define IDC_DC_QC_ZVAL                  1049
#define IDC_DC_QC_SPOTSIZE              1050
#define IDC_DC_QC_READ_ALPHA            1051
#define IDC_DC_QC_WRITE_ALPHA           1052
#define IDC_DC_QC_READ_ZVAL             1053
#define IDC_DC_QC_WRITE_ZVAL            1054
#define IDC_DC_QUICK_CONTROL            1055
#define IDC_DC_RECORDMODES              1056
#define IDC_DC_TRACKMODES               1057
#define IDC_DC_CALIBRATION_TRACKING     1058
#define IDC_DC_QC_READ_CURRENT          1059
#define IDC_DC_QC_CAMLEN2               1060
#define IDC_DC_QC_READ_SPOTSIZE         1061
#define IDC_DC_COLLECT_FRAMES           1062
#define IDC_DC_QC_TOGBLANKING           1063
#define IDC_DC_QC_TOGLARGESCREEN        1064
#define IDC_DC_QC_READ_CAMLENGTH        1065
#define IDC_DC_BIAS                     1066
#define IDC_DC_QC_WRITE_EMISSIONSTEP    1067
#define IDC_DC_EXPOSURE                 1068
#define IDC_DC_QC_TOGPARALLEL           1069
#define IDC_DC_STATIC_GAIN              1070
#define IDC_DC_STATIC_BIAS              1071
#define IDC_DC_STATIC_EXP               1072
#define IDC_DC_CB_INVERTED              1073
#define IDC_DC_QC_GO_ALPHA              1074
#define IDC_DC_QC_GO_Z                  1075
#define IDC_MFCBUTTON1                  1076
#define IDC_DC_QC_SPEED_70              1076
#define IDC_DC_CRYSTAL_NAME             1077
#define IDC_DC_CRYSTAL_ID               1078
#define IDC_DC_NUM_OF_FRAMES_TO_TAKE    1079
#define IDC_DC_OPERATOR_NAME            1080
#define IDC_BUTTON1                     1080
#define IDC_DC_QC_SPEED_50              1081
#define IDC_TAB1                        1082
#define IDC_DC_CRYSTAL_ID_EXTRA         1082
#define IDC_DC_QC_SPEED_40              1083
#define IDC_DC_QC_SPEED_71              1084
#define IDC_DC_QC_SPEED_20              1084
#define IDC_DC_QC_SPEEDXY_80            1085
#define IDC_DC_QC_SPEEDXY_50            1086
#define IDC_DC_QC_SPEEDXY_20            1087
#define IDC_DC_QC_SPEED_21              1088
#define IDC_DC_QC_SPEEDXY_5             1088
#define IDC_DC_CALIB_BEAM               1089
#define IDC_DC_IMG_EXPTIME              1091
#define IDC_DC_IMG_GAIN                 1092
#define IDC_DC_IMG_BIAS                 1093
#define IDC_DC_SAVE_SEARCH_BTN          1094
#define IDC_DC_SAVE_IMGING_BTN          1095
#define IDC_DC_SAVE_DIFF_BTN            1096
#define IDC_DC_LOAD_SEARCH_BTN          1097
#define IDC_DC_LOAD_IMGING_BTN          1098
#define IDC_DC_LOAD_DIFF_BTN            1099
#define IDC_DC_FIND_Z_HEIGHT_CHCKBTN    1100
#define IDC_DC_TPX_RESET                1101
#define IDC_DC_TPX_RESETCHIPS           1102
#define IDC_LENS_CTRL_BTN               1103
#define IDC_DC_DO_TRACKING              1104
#define IDC_DC_RECORD_IMG_STEPS         1105
#define IDC_DC_RECORD_NEW_IMGS          1106
#define IDC_DC_RECORD_STEPWISE          1106
#define IDC_DC_RECORD_IMG_STEPS_VARIABLE 1107
#define IDC_DC_PRECESSION               1108
#define IDC_DC_INTERVAL_FROM            1109
#define IDC_DC_INTERVAL_TO              1110
#define IDC_DC_RECORD_VARIABLE_STEP     1111
#define IDC_DC_QC_CHANGE_CAMLEN         1112
#define IDC_DC_QC_CHANGE_BRIGHTNESS     1113
#define IDC_DC_FINE_CALIB               1114
#define IDC_DC_CORRECT_CALIBRATION      1114
#define IDC_DC_BLANK_ROT                1115
#define IDC_DC_UPDATE_RECORD_INFO       1118
#define IDC_DC_SAVE_RAW_IMG             1119
#define IDC_DC_CALIBRATE_DELTA          1120
#define IDC_DC_CALIBRATION_DELTA        1120
#define IDC_DC_DELTA_CALIB_LBL          1121
#define IDC_CHECK1                      1122
#define IDC_DC_SAVE_LENS_PARAMS         1122
#define IDC_CHECK2                      1124
#define IDC_DC_CB_LIVEFFT               1124
#define IDC_DC_QC_2DRadar               1125
#define IDC_DC_NUMREGIONS               1126
#define IDC_DC_SERIALEDDURATION         1127
#define IDC_DC_SCANREGIONS              1128
#define IDC_DC_TRACKSTAGE_CHCKBTN       1129
#define IDC_DC_CB_SHOWRINGS             1130
#define IDC_DC_CB_SHOWPEAKS             1131
#define IDC_DC_SERIALED_DMAX            1132
#define IDC_DC_SERIALED_YSTEPS          1133
#define IDC_DC_SERIALED_MINPEAKS        1134
#define IDC_DC_SERIALED_QUALITYLEVEL    1135
#define IDC_DC_SERIALED_THRESHOLD_OR_PEAKDISTANCE    1135
#define IDC_DC_SERIALED_ADDFOVTOREGION  1136
#define IDC_DC_SERIALED_CAPTUREREGIONSFROMIMAGE 1137
#define IDC_DC_SERIALED_PEAKSIZE        1138
#define IDC_DC_SERIALED_I_SIGMA         1139
#define ID_MENU_DATACOLLECTION          32771
#define ID_MENU_QUIT                    32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
